### PR TITLE
Add superfast documentation and couposing documentation

### LINKED ISSUE #36: Update SuperFast documentation
https://github.com/EarthSciML/GasChem.jl/blob/c9562f3566e53194e21183b33ae5415a766a61d4/docs/src/index.md?plain=1#L12

Update to reflect new version. Also update so that figures are automatically generated [like this](https://github.com/EarthSciML/Aerosol.jl/blob/a0d51441147b39cae501fa3b27fcfee5108d1834/docs/src/isorropia/examples.md?plain=1#L172) rather than being saved ahead of time.  Some documentation about how to do this is [here](https://documenter.juliadocs.org/stable/man/syntax/#@example-block).

### PR DESCRIPTION
**Pull request by jialinl6**
Fixes #36 

Captures https://github.com/EarthSciML/GasChem.jl/issues/36

### CODE REVIEW

**Comment by jialinl6** [comment]
After several attempts, I discovered that the documentation test can only be passed by adding the following lines at the beginning of the 'index.md' file.

```@autodocs
Modules = [GasChem]
```

**Comment by jialinl6** [comment]
I also combined the @example blocks and @setup blocks in the markdown file to hide some output from the final website, and it works well locally. Corresponding updates have been applied to other documentation files and are reflected in the other open pull requests."

**Comment by ctessum** [comment]
## <a href="https://gov4git.org">This project is governed with Gov4Git.</a> Gov4Git notices
On `Saturday, 02-Mar-24 01:13:17 UTC` by Gov4Git `dev`

#### Notice `2uugci`
Started managing this PR as Gov4Git proposal `41` with initial __approval score__ of `0.000000`.

This project is managed by [Gov4Git](https://gov4git.org), a decentralized governance system for collaborative git projects.
To participate in governance, __install the [Gov4Git desktop app](https://github.com/gov4git/desktop-application)__.

**Review by ctessum — APPROVED** [review]

**Review by ctessum — APPROVED** [review]

**Comment by ctessum** [comment]
## <a href="https://gov4git.org">This project is governed with Gov4Git.</a> Gov4Git notices
On `Thursday, 07-Mar-24 14:23:06 UTC` by Gov4Git `dev`

#### Notice `vqc7hd`
This PR, managed as Gov4Git proposal `41`, has been closed 🎉

The PR approval tally was `0.000000`.

Bounty of `0.000000` credits was donated to the community's matching fund.

Resolved issues:

Rewarded PR reviewers:

Tally breakdown by user:

**Pull request merged**
